routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::view('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('associations','AssociationController');
Route::resource('pass_throughs','PassThroughController');

app/Association.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Http\Traits\Hashidable;

class Association extends Model
{
    use Hashidable;
    
    protected $fillable=([
        'initials',
        'name',
        'cnpj',
        'campus',
        'cep',
        'full_adress',
        'complement',
        'neighborhood',
        'city',
        'state',
        'phone',
        'phone2',
        'cellphone',
        'email',
        'email2',
        'contact',
        'association_status_id',
    ]);

    public function associationStatus() {
        return $this->belongsTo(associationStatus::class);
    }
}

app/Http/Controllers/AssociationController.php
<?php

namespace App\Http\Controllers;

use App\Association;
use Illuminate\Http\Request;
use Hashids\Hashids;

class AssociationController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('association.index')->with(['associations'=>Association::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('association.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'initials' => "required",
            'name' => "required",
            'cnpj' => "required",
            'campus' => "required",
            'cep' => "required",
            'full_adress' => "required",
            'complement' => "required",
            'neighborhood' => "required",
            'city' => "required",
            'state' => "required",
            'phone' => "required",
            'phone2' => "required",
            'cellphone' => "required",
            'email' => "required",
            'email2' => "required",
            'contact' => "required",
        ]);

        $association = new Association([
            'initials' => $request->get('initials'),
            'name' => $request->get('name'),
            'cnpj' => $request->get('cnpj'),
            'campus' => $request->get('campus'),
            'cep' => $request->get('cep'),
            'full_adress' => $request->get('full_adress'),
            'complement' => $request->get('complement'),
            'neighborhood' => $request->get('neighborhood'),
            'city' => $request->get('city'),
            'state' => $request->get('state'),
            'phone' => $request->get('phone'),
            'phone2' => $request->get('phone2'),
            'cellphone' => $request->get('cellphone'),
            'email' => $request->get('email'),
            'email2' => $request->get('email2'),
            'contact' => $request->get('contact'),
            'association_status_id' => 1,
        ]);
        $association->save();
        
        
        return view('association.show')->with(['association'=>$association,'id_hashed'=>$id_hashed]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Association  $association
     * @return \Illuminate\Http\Response
     */
    public function show(Association $association)
    {

        return view('association.show')->with(['association'=>$association]);        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Association  $association
     * @return \Illuminate\Http\Response
     */
    public function edit(Association $association)
    {
        return view('association.edit')->with(['association'=>$association]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Association  $association
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Association $association)
    {
        $request->validate([
            'initials' => "required",
            'name' => "required",
            'cnpj' => "required",
            'campus' => "required",
            'cep' => "required",
            'full_adress' => "required",
            'complement' => "required",
            'neighborhood' => "required",
            'city' => "required",
            'state' => "required",
            'phone' => "required",
            'phone2' => "required",
            'cellphone' => "required",
            'email' => "required",
            'email2' => "required",
            'contact' => "required",
            'association_status_id' => "required",
        ]);

        $association->initials = $request->get('initials');
        $association->name = $request->get('name');
        $association->cnpj = $request->get('cnpj');
        $association->campus = $request->get('campus');
        $association->cep = $request->get('cep');
        $association->full_adress = $request->get('full_adress');
        $association->complement = $request->get('complement');
        $association->neighborhood = $request->get('neighborhood');
        $association->city = $request->get('city');
        $association->state = $request->get('state');
        $association->phone = $request->get('phone');
        $association->phone2 = $request->get('phone2');
        $association->cellphone = $request->get('cellphone');
        $association->email = $request->get('email');
        $association->email2 = $request->get('email2');
        $association->contact = $request->get('contact');
        $association->association_status_id = $request->get('association_status_id');

        $association->save();

        return view('association.show',['association'=>$association]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Association  $association
     * @return \Illuminate\Http\Response
     */
    public function destroy(Association $association)
    {
        //
    }
}

resources/views/association/create.blade.php
@extends('adminlte::page')


@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"
integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
crossorigin="anonymous"></script>
<!-- Adicionando Javascript -->
<script type="text/javascript" >

    $(document).ready(function() {

        function limpa_formulário_cep() {
            // Limpa valores do formulário de cep
            $("#rua").val("");
            $("#bairro").val("");
            $("#cidade").val("");
            $("#uf").val("");
            //$("#ibge").val("");
        }
        
        //Quando o campo cep perde o foco
        $("#cep").blur(function() {

            //Nova variável "cep" somente com dígitos
            var cep = $(this).val().replace(/\D/g, '');

            //Verifica se campo cep possui valor informado
            if (cep != "") {

                //Expressão regular para validar o CEP
                var validacep = /^[0-9]{8}$/;

                //Valida o formato do CEP.
                if(validacep.test(cep)) {

                    //Preenche os campos com "..." enquanto consulta webservice
                    $("#rua").val("...");
                    $("#bairro").val("...");
                    $("#cidade").val("...");
                    $("#uf").val("...");
                    //$("#ibge").val("...");

                    //Consulta o webservice viacep.com.br/
                    $.getJSON("https://viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                        if (!("erro" in dados)) {
                            //Atualiza os campos com os valores da consulta.
                            $("#rua").val(dados.logradouro);
                            $("#bairro").val(dados.bairro);
                            $("#cidade").val(dados.localidade);
                            // $('#uf option[value='+dados.uf+']').eq(optionIndex).prop('selected',true);
                            $("#uf").val(dados.uf);
                            //$("#ibge").val(dados.ibge);
                        } //end if.
                        else {
                            //CEP pesquisado não foi encontrado.
                            limpa_formulário_cep();
                            alert("CEP não encontrado.");
                        }
                    });
                } //end if.
                else {
                    //cep é inválido.
                    limpa_formulário_cep();
                    alert("Formato de CEP inválido.");
                } 
            } //end if.
            else {
                //cep sem valor, limpa formulário.
                limpa_formulário_cep();
            }
        });

        //SP CELPHONES
        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
        spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };

        $('.sp_celphones').mask(SPMaskBehavior, spOptions);
        
        //CPF/CNPJ
        var comportamentoCpfCnpj = function (val) {
            return val.replace(/\D/g, '').length < 12 ?  '000.000.000-009999':'000.000.000/0099-99';
        },
        cpfCnpjOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(comportamentoCpfCnpj.apply({}, arguments), options);
            }
        };

        $('.cpf_cnpj').mask(comportamentoCpfCnpj, cpfCnpjOptions);
    });

</script>
<div class="col-md-6">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h2 class="box-title">Nova associação</h2>
        </div>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br />
        @endif
        <form method="post" action="{{ route('associations.store') }}">
            <div class="box-body">
                <div class="form-group {{ $errors->has('initials') ? 'has-error' : '' }}">
                    @csrf

                    <label for="initials"> Sigla</label>
                    <input 
                        type="text" 
                        class="form-control" 
                        name="initials"
                        value="{{old('initials')}}"
                    />
                    @if ($errors->has('initials'))
                        <span class="help-block">
                            <strong>{{ $errors->first('initials') }}</strong>
                        </span>
                    @endif
                </div>
                    
                <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                    <label for="name"> Nome</label>
                    <input 
                        type="text" 
                        class="form-control" 
                        name="name"
                        value="{{old('name')}}"
                    />

                    @if($errors->has('name'))
                        <span class="help-block">
                            <strong>{{$errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
                    
                <div class="form-group">
                    <label for="cnpj"> CNPJ</label>
                    <input
                        type="text"
                        class="form-control cnpj"
                        name="cnpj"
                        value="{{old('cnpj')}}"
                    />
                </div>
                    
                <div class="form-group">
                    <label for="campus"> Campus</label>
                    <input
                        type="text"
                        class="form-control"
                        name="campus"
                        value="{{old('campus')}}"
                    />
                </div>
                    
                <div class="form-group">
                    <label for="cep"> Cep</label>
                    <input
                        type="text"
                        class="form-control"
                        id="cep"
                        name="cep"
                        value="{{old('cep')}}"
                        data-mask="00000-000"
                    />
                </div>
                    
                <div class="form-group">
                    <label for="full_adress"> Endereço + número</label>
                    <input
                        type="text"
                        class="form-control"
                        id="rua"
                        name="full_adress"
                        value="{{old('full_adress')}}"
                    />
                </div>
                    
                <div class="form-group">
                    <label for="complement"> Complemento:</label>
                    <input
                        type="text"
                        class="form-control"
                        name="complement"
                        value="{{old('complement')}}"
                    />
                </div>
                    
                <div class="form-group">
                    <label for="neighborhood"> Bairro</label>
                    <input
                        type="text"
                        class="form-control"
                        name="neighborhood"
                        id="bairro"
                        value="{{old('neighborhood')}}"
                    />
                </div>
                    
                <div class="form-group">
                    <label for="city"> Cidade</label>
                    <input
                        type="text"
                        class="form-control"
                        name="city"
                        id="cidade"
                        value="{{old('city')}}"
                    />
                </div>
                    
                <div class="form-group">
                    <label for="state"> UF</label>
                    <input
                        type="text"
                        class="form-control"
                        id="uf"
                        name="state"
                        data-mask="AA"
                        value="{{old('state')}}"
                    />
                </div>
                    
                <div class="form-group">
                    <label for="phone"> Telefone</label>
                    <input
                        type="text"
                        class="form-control sp_celphones"
                        name="phone"
                        value="{{old('phone')}}"
                    />
                </div>

                <div class="form-group">
                    <label for="phone2"> Telefone 2</label>
                    <input
                        type="text"
                        class="form-control sp_celphone2s"
                        name="phone2"
                        value="{{old('phone2')}}"
                    />
                </div>
                    
                <div class="form-group">
                    <label for="cellphone"> Celular</label>
                    <input
                        type="text"
                        class="form-control sp_celphones"
                        name="cellphone"
                        value="{{old('cellphone')}}"
                    />
                </div>
                    
                <div class="form-group">
                    <label for="email"> Email</label>
                    <input
                        type="text"
                        class="form-control"
                        name="email"
                        value="{{old('email')}}"
                    />
                </div>
                    
                <div class="form-group">
                    <label for="email2"> Email 2</label>
                    <input
                        type="text"
                        class="form-control"
                        name="email2"
                        value="{{old('email2')}}"
                    />
                </div>
                    
                <div class="form-group">
                    <label for="contact"> Contato</label>
                    <input
                        type="text"
                        class="form-control"
                        name="contact"
                        value="{{old('contact')}}"
                    />
                </div>

                <button type="submit" class="btn btn-primary">Adicionar</button>
            </div>
        </form>
    </div>
</div>
<div class="clearfix"></div>
@endsection

resources/views/association/edit.blade.php
@extends('adminlte::page')


@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"
integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
crossorigin="anonymous"></script>
<!-- Adicionando Javascript -->
<script type="text/javascript" >

    $(document).ready(function() {

        function limpa_formulário_cep() {
            // Limpa valores do formulário de cep.
            $("#rua").val("");
            $("#bairro").val("");
            $("#cidade").val("");
            $("#uf").val("");
            //$("#ibge").val("");
        }
        
        //Quando o campo cep perde o foco.
        $("#cep").blur(function() {

            //Nova variável "cep" somente com dígitos.
            var cep = $(this).val().replace(/\D/g, '');

            //Verifica se campo cep possui valor informado.
            if (cep != "") {

                //Expressão regular para validar o CEP.
                var validacep = /^[0-9]{8}$/;

                //Valida o formato do CEP.
                if(validacep.test(cep)) {

                    //Preenche os campos com "..." enquanto consulta webservice.
                    $("#rua").val("...");
                    $("#bairro").val("...");
                    $("#cidade").val("...");
                    $("#uf").val("...");
                    //$("#ibge").val("...");

                    //Consulta o webservice viacep.com.br/
                    $.getJSON("https://viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                        if (!("erro" in dados)) {
                            //Atualiza os campos com os valores da consulta.
                            $("#rua").val(dados.logradouro);
                            $("#bairro").val(dados.bairro);
                            $("#cidade").val(dados.localidade);
                            // $('#uf option[value='+dados.uf+']').eq(optionIndex).prop('selected',true);
                            $("#uf").val(dados.uf);
                            //$("#ibge").val(dados.ibge);
                        } //end if.
                        else {
                            //CEP pesquisado não foi encontrado.
                            limpa_formulário_cep();
                            alert("CEP não encontrado.");
                        }
                    });
                } //end if.
                else {
                    //cep é inválido.
                    limpa_formulário_cep();
                    alert("Formato de CEP inválido.");
                } 
            } //end if.
            else {
                //cep sem valor, limpa formulário.
                limpa_formulário_cep();
            }
        });
        //celular com 9 na frente
        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
        spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };

        $('.sp_celphones').mask(SPMaskBehavior, spOptions);


        //CPF/CNPJ
        var comportamentoCpfCnpj = function (val) {
            return val.replace(/\D/g, '').length < 12 ?  '000.000.000-009999':'000.000.000/0099-99';
        },
        cpfCnpjOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(comportamentoCpfCnpj.apply({}, arguments), options);
            }
        };

        $('.cpf_cnpj').mask(comportamentoCpfCnpj, cpfCnpjOptions);
    });

</script>
<div class="col-md-6">
    <div class="box box-danger">
        <div class="box-header with-border">
            <h2 class="box-title">Edição de Associação ({{ $association->initials }})</h2>

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
        </div>  
        <form method="post" action="{{ route('associations.update', Hashids::connection('association')->encode($association->id)) }}" enctype="multipart/form-data">
            <div class="box-body">
                @method('PATCH')
                @csrf
                <div class="form-group {{ $errors->has('initials') ? 'has-error' : '' }}">
                    <label for="initials">Sigla</label>
                    <input type="text" class="form-control" name="initials" value="{{ $association->initials }}" />

                    @if($errors->has('initials'))
                        <span class="help-block">
                            <strong>
                                {{$errors->first('initials')}}
                            </strong>
                        </span>
                    @endif
                </div>
                <div class="form-group">
                    <label for="name">Nome</label>
                    <input type="text" class="form-control" name="name" value="{{ $association->name }}" />
                </div>
                <div class="form-group">
                    <label for="cnpj">CNPJ</label>
                    <input type="text" class="form-control cpf_cnpj" name="cnpj" value="{{ $association->cnpj }}" />
                </div>
                <div class="form-group">
                    <label for="campus">Campus</label>
                    <input type="text" class="form-control" name="campus" value="{{ $association->campus }}" />
                </div>
                <div class="form-group">
                    <label for="cep">CEP</label>
                    <input type="text" class="form-control" name="cep" id="cep" data-mask="00000-000" value="{{ $association->cep }}" />
                </div>
                <div class="form-group">
                    <label for="full_adress">Endereço + número</label>
                    <input type="text" class="form-control" name="full_adress" id="rua" value="{{ $association->full_adress }}" />
                </div>
                <div class="form-group">
                    <label for="complement">Complemento</label>
                    <input type="text" class="form-control" name="complement" value="{{ $association->complement }}" />
                </div>
                <div class="form-group">
                    <label for="neighborhood">Bairro</label>
                    <input type="text" class="form-control" name="neighborhood" id="bairro" value="{{ $association->neighborhood }}" />
                </div>
                <div class="form-group">
                    <label for="city">Cidade</label>
                    <input type="text" class="form-control" name="city" id="cidade" value="{{ $association->city }}" />
                </div>
                <div class="form-group">
                    <label for="state">UF</label>
                    <input type="text" class="form-control" name="state" id="uf" value="{{ $association->state }}" />
                </div>
                <div class="form-group">
                    <label for="phone">Telefone</label>
                    <input type="text" class="form-control sp_celphones" name="phone" value="{{ $association->phone }}" />
                </div>
                <div class="form-group">
                    <label for="phone2">Telefone 2</label>
                    <input type="text" class="form-control sp_celphones" name="phone2" value="{{ $association->phone2 }}" />
                </div>
                <div class="form-group">
                    <label for="cellphone">Celular / Whatsapp</label>
                    <input type="text" class="form-control sp_celphones" name="cellphone" value="{{ $association->cellphone }}" />
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" name="email" value="{{ $association->email }}" />
                </div>
                <div class="form-group">
                    <label for="email2">Email 2</label>
                    <input type="text" class="form-control" name="email2" value="{{ $association->email2 }}" />
                </div>
                <div class="form-group">
                    <label for="contact">Contato</label>
                    <input type="text" class="form-control" name="contact" value="{{ $association->contact }}" />
                </div>
                
                <div class="form-group">
                    <label for="association_status_id">Status</label>
                    <select type="text" class="form-control select2" name="association_status_id">
                        @foreach(App\AssociationStatus::all() as $associationStatus)
                            <option value="{{$associationStatus->id}}" 
                                @if($association->association_status_id==$associationStatus->id)
                                    selected
                                @endif    
                            >{{$associationStatus->description}}</option>
                        @endforeach
                    </select>
                </div>
                
                <button type="submit" class="btn btn-primary">Salvar</button>
            
        </form>
        </div>
    </div>
</div>
<div class="clearfix"></div>
@endsection

resources/views/association/index.blade.php
@extends('adminlte::page')

@section('content_header')
@endsection

@section('content')

@push('css')
<style>
    .uper {
        margin-top: 40px;
    }
</style>
@if(session()->get('success'))
    <div class="alert alert-success">
    {{ session()->get('success') }}  
    </div><br />
@endif
<div class="col-md-6">
    
    <div class="box box-primary">
        <div class="box-header with-border">
            <h2 class="box-title">Associações ativas</h2>
            
        </div>
        <div class="box-body">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Sigla</th>
                        <th>Nome</th>
                        <th width="40"> </th>
                    </tr>
                </thead>
                @foreach($associations as $association)
                    <tr>
                        <td> {{$association->initials}} </td>
                        <td> {{$association->name}} </td>
                        <td>
                            <a class="table-row btn btn-primary" href="{{ route('associations.show',Hashids::connection('association')->encode($association->id))}}">
                                Detalhes
                            </a>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="box box-success">
        <div class="box-header with-border">
            <h2 class="box-title">Pesquisar(em construção)</h2>
        </div>
        <div class="box-body with-border">
            <div class="form-group">
                <input class="form-control" type="text" name="pesquisar" id="" placeholder="Pesquisar cliente">
            </div>
        </div>
        <div class="box-header with-border">
            <h2 class="box-title">Ações</h2>
        </div>
        <div class="box-body with-border">
            <a href={{ route('associations.create')}} class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>
                Novo
            </a>
        </div>
        <div class="box-header with-border">
            <h2 class="box-title">Listar(em construção)</h2>
        </div>
        <div class="box-body">
            <a href="#" class="btn btn-danger">
                Inativos
            </a>
            <a href="#" class="btn btn-success">
                Ativos
            </a>
            <a href="#" class="btn btn-warning">
                Inadimplentes
            </a>
            <a href="#" class="btn btn-primary">
                Maiores
            </a>

        </div>
    </div>
</div>
<div class="clearfix"></div>
@endsection

resources/views/association/layout.blade.php
@extends('adminlte::page')
@section('content')

  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
  @yield('content_client')
  <div class="clearfix"></div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>


@endsection