routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::view('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('associations','AssociationController');
Route::resource('pass_throughs','PassThroughController');

app/PassThrough.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PassThrough extends Model
{
    protected $fillable=([
        'association_id',
        'payment_date',
        'competence',
        'pass_through_plan_id',
        'holders_amount',
        'unitary_value',
        'extra_value',
        'total_value',
        'pass_through_payment_type_id',
        'pass_through_status_id',
        'document',
    ]);

    public function passThroughPaymentType() {
        return $this->belongsTo(PassThroughPaymentType::class);
    }

    public function association() {
        return $this->belongsTo(Association::class);
    }

    public function passThroughStatus() {
        return $this->belongsTo(PassThroughStatus::class);
    }

    public function passThroughPlan() {
        return $this->belongsTo(PassThroughPlan::class);
    }

}

app/Http/Controllers/PassThroughController.php
<?php

namespace App\Http\Controllers;

use App\PassThrough;
use Illuminate\Http\Request;

class PassThroughController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pass_through.index')->with(['pass_throughs'=>PassThrough::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pass_through.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\PassThrough  $passThrough
     * @return \Illuminate\Http\Response
     */
    public function show(PassThrough $passThrough)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\PassThrough  $passThrough
     * @return \Illuminate\Http\Response
     */
    public function edit(PassThrough $passThrough)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\PassThrough  $passThrough
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, PassThrough $passThrough)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\PassThrough  $passThrough
     * @return \Illuminate\Http\Response
     */
    public function destroy(PassThrough $passThrough)
    {
        //
    }
}

resources/views/pass_through/create.blade.php
@extends('adminlte::page')


@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"
integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
crossorigin="anonymous"></script>

<div class="col-md-6">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h2 class="box-title">Novo repasse</h2>
        </div>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br />
        @endif
        <form method="post" action="{{ route('associations.store') }}">
            <div class="box-body">
                
                @csrf
                <div class="form-group">
                    <label for="association_id">Associação</label>
                    <select name="association_id" id="association_id" class="form-control">
                        <option value="">Selecione</option>

                        @foreach(App\Association::all() as $association)
                            <option value="{{$association->id}}"
                                @if($association->id==old('association_id'))
                                    selected
                                @endif
                                >
                                {{$association->initials}}
                                -
                                {{$association->name}}
                            </option>
                        @endforeach

                    </select>
                </div>
                    
                <div class="form-group {{ $errors->has('payment_date') ? 'has-error' : ''}}">
                    <label for="payment_date"> Data Pagamento</label>
                    <input 
                        type="date" 
                        class="form-control" 
                        name="payment_date"
                        value="{{old('payment_date')}}"
                    />

                    @if($errors->has('payment_date'))
                        <span class="help-block">
                            <strong>{{$errors->first('payment_date') }}</strong>
                        </span>
                    @endif
                </div>
                
                <div class="form-group {{ $errors->has('competence') ? 'has-error' : ''}}">
                    <label for="competence"> Data Competência</label>
                    <input 
                        type="date" 
                        class="form-control" 
                        name="competence"
                        value="{{old('competence')}}"
                    />

                    @if($errors->has('competence'))
                        <span class="help-block">
                            <strong>{{$errors->first('competence') }}</strong>
                        </span>
                    @endif
                </div>
                    
                <div class="form-group">
                    <label for="pass_through_plan_id">Plano</label>
                    <select name="pass_through_plan_id" id="pass_through_plan_id" class="form-control">
                        <option value="">Selecione</option>

                        @foreach(App\PassThroughPlan::all() as $pass_through_plan)
                            <option value="{{$pass_through_plan->id}}"
                                @if($pass_through_plan->id==old('pass_through_plan_id'))
                                    selected
                                @endif
                                >
                                {{$pass_through_plan->description}}
                            </option>
                        @endforeach

                    </select>
                </div>
                    
                <div class="form-group {{ $errors->has('holders_amount') ? 'has-error' : ''}}">
                    <label for="holders_amount"> Quantidade de titulares</label>
                    <input 
                        type="number" 
                        class="form-control" 
                        name="holders_amount"
                        value="{{old('holders_amount')}}"
                    />

                    @if($errors->has('holders_amount'))
                        <span class="help-block">
                            <strong>{{$errors->first('holders_amount') }}</strong>
                        </span>
                    @endif
                </div>
                    
                <div class="form-group {{ $errors->has('unitary_value') ? 'has-error' : ''}}">
                    <label for="unitary_value"> Valor unitário</label>
                    <input 
                        type="text" 
                        class="form-control valor" 
                        name="unitary_value"
                        value="{{old('unitary_value')}}"
                    />

                    @if($errors->has('unitary_value'))
                        <span class="help-block">
                            <strong>{{$errors->first('unitary_value') }}</strong>
                        </span>
                    @endif
                </div>
                    
                <div class="form-group {{ $errors->has('extra_value') ? 'has-error' : ''}}">
                    <label for="extra_value"> Valor extra</label>
                    <input 
                        type="text" 
                        class="form-control valor" 
                        name="extra_value"
                        value="{{old('extra_value')}}"
                    />

                    @if($errors->has('extra_value'))
                        <span class="help-block">
                            <strong>{{$errors->first('extra_value') }}</strong>
                        </span>
                    @endif
                </div>
                    
                <div class="form-group {{ $errors->has('total_value') ? 'has-error' : ''}}">
                    <label for="total_value"> Valor total</label>
                    <input 
                        type="text" 
                        class="form-control valor" 
                        name="total_value"
                        value="{{old('total_value')}}"
                    />

                    @if($errors->has('total_value'))
                        <span class="help-block">
                            <strong>{{$errors->first('total_value') }}</strong>
                        </span>
                    @endif
                </div>
                
                <div class="form-group">
                    <label for="pass_through_payment_type_id">Tipo de pagamento</label>
                    <select name="pass_through_payment_type_id" id="pass_through_payment_type_id" class="form-control">
                        <option value="">Selecione</option>

                        @foreach(App\PassThroughPaymentType::all() as $pass_through_payment_type)
                            <option value="{{$pass_through_payment_type->id}}"
                                @if($pass_through_payment_type->id==old('pass_through_payment_type_id'))
                                    selected
                                @endif
                                >
                                {{$pass_through_payment_type->description}}
                            </option>
                        @endforeach

                    </select>
                </div>
                
                <div class="form-group">
                    <label for="pass_through_status_id">Status pagamento</label>
                    <select name="pass_through_status_id" id="pass_through_status_id" class="form-control">
                        <option value="">Selecione</option>

                        @foreach(App\PassThroughStatus::all() as $pass_through_status)
                            <option value="{{$pass_through_status->id}}"
                                @if($pass_through_status->id==old('pass_through_status_id'))
                                    selected
                                @endif
                                >
                                {{$pass_through_status->description}}
                            </option>
                        @endforeach

                    </select>
                </div>
                
                <div class="form-group {{ $errors->has('document') ? 'has-error' : ''}}">
                    <label for="document"> Documento</label>
                    <input 
                        type="text" 
                        class="form-control" 
                        name="document"
                        value="{{old('document')}}"
                    />

                    @if($errors->has('document'))
                        <span class="help-block">
                            <strong>{{$errors->first('document') }}</strong>
                        </span>
                    @endif
                </div>

                <button type="submit" class="btn btn-primary">Adicionar</button>
            </div>
        </form>
    </div>
</div>
<div class="clearfix"></div>
@endsection

resources/views/pass_through/edit.blade.php
@extends('adminlte::page')


@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"
integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
crossorigin="anonymous"></script>
<!-- Adicionando Javascript -->
<script type="text/javascript" >

    $(document).ready(function() {

        function limpa_formulário_cep() {
            // Limpa valores do formulário de cep.
            $("#rua").val("");
            $("#bairro").val("");
            $("#cidade").val("");
            $("#uf").val("");
            //$("#ibge").val("");
        }
        
        //Quando o campo cep perde o foco.
        $("#cep").blur(function() {

            //Nova variável "cep" somente com dígitos.
            var cep = $(this).val().replace(/\D/g, '');

            //Verifica se campo cep possui valor informado.
            if (cep != "") {

                //Expressão regular para validar o CEP.
                var validacep = /^[0-9]{8}$/;

                //Valida o formato do CEP.
                if(validacep.test(cep)) {

                    //Preenche os campos com "..." enquanto consulta webservice.
                    $("#rua").val("...");
                    $("#bairro").val("...");
                    $("#cidade").val("...");
                    $("#uf").val("...");
                    //$("#ibge").val("...");

                    //Consulta o webservice viacep.com.br/
                    $.getJSON("https://viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                        if (!("erro" in dados)) {
                            //Atualiza os campos com os valores da consulta.
                            $("#rua").val(dados.logradouro);
                            $("#bairro").val(dados.bairro);
                            $("#cidade").val(dados.localidade);
                            // $('#uf option[value='+dados.uf+']').eq(optionIndex).prop('selected',true);
                            $("#uf").val(dados.uf);
                            //$("#ibge").val(dados.ibge);
                        } //end if.
                        else {
                            //CEP pesquisado não foi encontrado.
                            limpa_formulário_cep();
                            alert("CEP não encontrado.");
                        }
                    });
                } //end if.
                else {
                    //cep é inválido.
                    limpa_formulário_cep();
                    alert("Formato de CEP inválido.");
                } 
            } //end if.
            else {
                //cep sem valor, limpa formulário.
                limpa_formulário_cep();
            }
        });
        //celular com 9 na frente
        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
        spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };

        $('.sp_celphones').mask(SPMaskBehavior, spOptions);


        //CPF/CNPJ
        var comportamentoCpfCnpj = function (val) {
            return val.replace(/\D/g, '').length < 12 ?  '000.000.000-009999':'000.000.000/0099-99';
        },
        cpfCnpjOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(comportamentoCpfCnpj.apply({}, arguments), options);
            }
        };

        $('.cpf_cnpj').mask(comportamentoCpfCnpj, cpfCnpjOptions);
    });

</script>
<div class="col-md-6">
    <div class="box box-danger">
        <div class="box-header with-border">
            <h2 class="box-title">Edição de Associação ({{ $association->initials }})</h2>

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
        </div>  
        <form method="post" action="{{ route('associations.update', Hashids::connection('association')->encode($association->id)) }}" enctype="multipart/form-data">
            <div class="box-body">
                @method('PATCH')
                @csrf
                <div class="form-group {{ $errors->has('initials') ? 'has-error' : '' }}">
                    <label for="initials">Sigla</label>
                    <input type="text" class="form-control" name="initials" value="{{ $association->initials }}" />

                    @if($errors->has('initials'))
                        <span class="help-block">
                            <strong>
                                {{$errors->first('initials')}}
                            </strong>
                        </span>
                    @endif
                </div>
                <div class="form-group">
                    <label for="name">Nome</label>
                    <input type="text" class="form-control" name="name" value="{{ $association->name }}" />
                </div>
                <div class="form-group">
                    <label for="cnpj">CNPJ</label>
                    <input type="text" class="form-control cpf_cnpj" name="cnpj" value="{{ $association->cnpj }}" />
                </div>
                <div class="form-group">
                    <label for="campus">Campus</label>
                    <input type="text" class="form-control" name="campus" value="{{ $association->campus }}" />
                </div>
                <div class="form-group">
                    <label for="cep">CEP</label>
                    <input type="text" class="form-control" name="cep" id="cep" data-mask="00000-000" value="{{ $association->cep }}" />
                </div>
                <div class="form-group">
                    <label for="full_adress">Endereço + número</label>
                    <input type="text" class="form-control" name="full_adress" id="rua" value="{{ $association->full_adress }}" />
                </div>
                <div class="form-group">
                    <label for="complement">Complemento</label>
                    <input type="text" class="form-control" name="complement" value="{{ $association->complement }}" />
                </div>
                <div class="form-group">
                    <label for="neighborhood">Bairro</label>
                    <input type="text" class="form-control" name="neighborhood" id="bairro" value="{{ $association->neighborhood }}" />
                </div>
                <div class="form-group">
                    <label for="city">Cidade</label>
                    <input type="text" class="form-control" name="city" id="cidade" value="{{ $association->city }}" />
                </div>
                <div class="form-group">
                    <label for="state">UF</label>
                    <input type="text" class="form-control" name="state" id="uf" value="{{ $association->state }}" />
                </div>
                <div class="form-group">
                    <label for="phone">Telefone</label>
                    <input type="text" class="form-control sp_celphones" name="phone" value="{{ $association->phone }}" />
                </div>
                <div class="form-group">
                    <label for="phone2">Telefone 2</label>
                    <input type="text" class="form-control sp_celphones" name="phone2" value="{{ $association->phone2 }}" />
                </div>
                <div class="form-group">
                    <label for="cellphone">Celular / Whatsapp</label>
                    <input type="text" class="form-control sp_celphones" name="cellphone" value="{{ $association->cellphone }}" />
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" name="email" value="{{ $association->email }}" />
                </div>
                <div class="form-group">
                    <label for="email2">Email 2</label>
                    <input type="text" class="form-control" name="email2" value="{{ $association->email2 }}" />
                </div>
                <div class="form-group">
                    <label for="contact">Contato</label>
                    <input type="text" class="form-control" name="contact" value="{{ $association->contact }}" />
                </div>
                
                <div class="form-group">
                    <label for="association_status_id">Status</label>
                    <select type="text" class="form-control select2" name="association_status_id">
                        @foreach(App\AssociationStatus::all() as $associationStatus)
                            <option value="{{$associationStatus->id}}" 
                                @if($association->association_status_id==$associationStatus->id)
                                    selected
                                @endif    
                            >{{$associationStatus->description}}</option>
                        @endforeach
                    </select>
                </div>
                
                <button type="submit" class="btn btn-primary">Salvar</button>
            
        </form>
        </div>
    </div>
</div>
<div class="clearfix"></div>
@endsection

resources/views/pass_through/index.blade.php
@extends('adminlte::page')

@section('content_header')
@endsection

@section('content')

@push('css')
<style>
    .uper {
        margin-top: 40px;
    }
</style>
@if(session()->get('success'))
    <div class="alert alert-success">
    {{ session()->get('success') }}  
    </div><br />
@endif
<div class="col-md-6">
    
    <div class="box box-primary">
        <div class="box-header with-border">
            <h2 class="box-title">Repasses</h2>
            
        </div>
        <div class="box-body">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Associação</th>
                        <th>Competência</th>
                        <th>Valor</th>
                        <th width="40"> </th>
                    </tr>
                </thead>
                @foreach($pass_throughs as $pass_through)
                    <tr>
                        <td> {{$pass_through->association->initials}} </td>
                        <td> {{$pass_through->competence}} </td>
                        <td> {{$pass_through->total_value}} </td>
                        <td>
                            <a class="table-row btn btn-primary" href="{{ route('pass_throughs.show',Hashids::connection('pass_through')->encode($pass_through->id))}}">
                                Detalhes
                            </a>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="box box-success">
        <div class="box-header with-border">
            <h2 class="box-title">Pesquisar(em construção)</h2>
        </div>
        <div class="box-body with-border">
            <div class="form-group">
                <input class="form-control" type="text" name="pesquisar" id="" placeholder="Pesquisar cliente">
            </div>
        </div>
        <div class="box-header with-border">
            <h2 class="box-title">Ações</h2>
        </div>
        <div class="box-body with-border">
            <a href={{ route('pass_throughs.create')}} class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>
                Novo
            </a>
        </div>
        <div class="box-header with-border">
            <h2 class="box-title">Listar(em construção)</h2>
        </div>
        <div class="box-body">
            <a href="#" class="btn btn-danger">
                Inativos
            </a>
            <a href="#" class="btn btn-success">
                Ativos
            </a>
            <a href="#" class="btn btn-warning">
                Inadimplentes
            </a>
            <a href="#" class="btn btn-primary">
                Maiores
            </a>

        </div>
    </div>
</div>
<div class="clearfix"></div>
@endsection

resources/views/pass_through/layout.blade.php
@extends('adminlte::page')
@section('content')

  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
  @yield('content_client')
  <div class="clearfix"></div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>


@endsection

resources/views/pass_through/show.blade.php
@extends('association.layout')

@section('content_header')
@endsection

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
  td:first-child{
      text-align:right;
      width:150px;
  }
</style>
<div class="col-md-6">
    <div class="box box-danger">
        <div class="box-header">
            <h2 class="box-title">Detalhes Associação</h2>
            @if(!empty($success))
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ $success }}  
                </div>
            @endif
        </div>
        <div class="box-body">
            <table class="table table-striped table-hover">
                <tbody>
                    <tr>
                        <td align="right">Sigla</td>
                        <td>{{$association->initials}}</td>
                    </tr>
                    <tr>
                        <td align="right">Nome</td>
                        <td>{{$association->name}}</td>
                    </tr>
                    <tr>
                        <td align="right">CNPJ</td>
                        <td>{{$association->cnpj}}</td>
                    </tr>
                    <tr>
                        <td align="right">Campus</td>
                        <td>{{$association->campus}}</td>
                    </tr>
                    <tr>
                        <td align="right">CEP</td>
                        <td>{{$association->cep}}</td>
                    </tr>
                    <tr>
                        <td align="right">Endereço + número</td>
                        <td>{{$association->full_adress}}</td>
                    </tr>
                    <tr>
                        <td align="right">Complemento</td>
                        <td>{{$association->complement}}</td>
                    </tr>
                    <tr>
                        <td align="right">Bairro</td>
                        <td>{{$association->neighborhood}}</td>
                    </tr>
                    <tr>
                        <td align="right">Cidade</td>
                        <td>{{$association->city}}</td>
                    </tr>
                    <tr>
                        <td align="right">UF</td>
                        <td>{{$association->state}}</td>
                    </tr>
                    <tr>
                        <td align="right">Telefone</td>
                        <td>{{$association->phone}}</td>
                    </tr>
                    <tr>
                        <td align="right">Telefone 2</td>
                        <td>{{$association->phone2}}</td>
                    </tr>
                    <tr>
                        <td align="right">Celular</td>
                        <td>{{$association->cellphone}}</td>
                    </tr>
                    <tr>
                        <td align="right">Email</td>
                        <td>{{$association->email}}</td>
                    </tr>
                    <tr>
                        <td align="right">Email 2</td>
                        <td>{{$association->email2}}</td>
                    </tr>
                    <tr>
                        <td align="right">Contato</td>
                        <td>{{$association->contact}}</td>
                    </tr>
                    <tr>
                        <td align="right">Status</td>
                        <td>{{$association->associationStatus->description}}</td>
                    </tr>
                    {{-- <tr>
                        <td align='right'>Cadastrado por:</td>
                        <td>{{$association->registerUser->name}}</td>
                    </tr>
                    <tr>
                        <td align='right'>Cadastrado em:</td>
                        <td>{{$association->created_at->format('d/m/Y H:i:s')}}</td>
                    </tr> --}}
                    <tr>
                        <td align='right'></td>
                        <td>
                            <a href="{{ route('associations.edit',Hashids::connection('association')->encode($association->id))}}" class="btn btn-primary">Editar</a>
                        </td>
                    </tr>
                </tbody>
                
            </table>
        </div>
    </div>
</div>
<div class="clearfix"></div>
@endsection